In [2]:
# Importng the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Importing the dataset
dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:2].values # converted into marix (independent variable X , NOT THE DEPENET variable y)
y = dataset.iloc[:, 2].values
dataset

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [4]:
# Splitting the dataset into the Training set and Test set
"""from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)"""

'from sklearn.cross_validation import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)'

In [5]:
# Feature Scaling
"""from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()"""

'from sklearn.preprocessing import StandardScaler\nsc_X = StandardScaler()\nX_train = sc_X.fit_transform(X_train)\nX_test = sc_X.transform(X_test)\nsc_y = StandardScaler()'

In [6]:
# Fitting the Regression Model(Decision tree model) to the dataset
# Create your regressor here
from sklearn.ensemble import RandomForestRegressor
rforest = RandomForestRegressor(n_estimators=100,random_state=0)
rforest.fit(X,y)

RandomForestRegressor(random_state=0)

In [7]:
y_pred = rforest.predict(np.array([[6.5]]))
y_pred

array([158300.])

In [8]:
# Fitting the Regression Model(Decision tree model) to the dataset
# Create your regressor here
from sklearn.ensemble import RandomForestRegressor
rforest = RandomForestRegressor(n_estimators=200,random_state=0)
rforest.fit(X,y)

RandomForestRegressor(n_estimators=200, random_state=0)

In [9]:
y_pred = rforest.predict(np.array([[6.5]]))
y_pred

array([159650.])

In [10]:
# Fitting the Regression Model(Decision tree model) to the dataset
# Create your regressor here
from sklearn.ensemble import RandomForestRegressor
rforest = RandomForestRegressor(n_estimators=300,random_state=0)
rforest.fit(X,y)

RandomForestRegressor(n_estimators=300, random_state=0)

In [11]:
y_pred = rforest.predict(np.array([[6.5]]))
y_pred

array([160333.33333333])

In [12]:
# Fitting the Regression Model(Decision tree model) to the dataset
# Create your regressor here
from sklearn.ensemble import RandomForestRegressor
rforest = RandomForestRegressor(n_estimators=400,random_state=0)
rforest.fit(X,y)

RandomForestRegressor(n_estimators=400, random_state=0)

In [13]:
y_pred = rforest.predict(np.array([[1.5]]))
y_pred

array([48500.])

In [14]:
from sklearn.metrics import mean_squared_error , r2_score

In [15]:
mean_squared_error(y,rforest.predict(X))

3849964203.125

In [16]:
r2_score(y,rforest.predict(X))

0.9522705577500628